Squashed AIRBIN generation and runtime
Xilinx/mlir-air pull request #128
Opened 2022-12-20 22:20 UTC by jgmelber

This PR adds initial runtime support for AIRBINs from [mlir-aie #243](https://github.com/Xilinx/mlir-aie/pull/243). AIRBIN generation and use is demonstrated in test/301_airbin_gen_add_one.

2022-12-21 01:45 UTC, fifield requested changes
I'm curious why we're checking in `.airbin` files instead of generating them?

2022-12-21 01:45 UTC, fifield commented on runtime_lib/airhost/CMakeLists.txt
> +set(INSTALLS airbin.cpp memory.cpp queue.cpp host.cpp utility.cpp pcie-ernic.cpp pcie-ernic-dev-mem-allocator.cpp network.cpp)
I think we can remove this line for good in a subsequent PR.

2022-12-21 01:45 UTC, fifield commented on runtime_lib/airhost/airbin.cpp
> +
Needs license

2022-12-21 01:45 UTC, fifield commented on runtime_lib/airhost/airbin.cpp
> +std::string to_air_cfg_name(uint32_t in) {
make this static?

2022-12-21 01:45 UTC, fifield commented on runtime_lib/airhost/include/airbin.h
> +#ifndef AIRBIN_H
needs license

2022-12-21 01:45 UTC, fifield commented on runtime_lib/airhost/include/airbin.h
> +void readairbin(std::ifstream &infile);
How does this relate to `air_load_airbin`? It should be a C API if it gets `#included` in `air_host.h` which is supposed to be a C header*. The alternative is to `#include` it in `air.hpp` which is much less desirable if these functions are required to use airbin.

\*  and `<string>` has already crept in

2022-12-21 01:45 UTC, fifield commented on test/278_portable_airbin_config/Makefile
> +.PHONY: all
needs license

2022-12-21 01:45 UTC, fifield commented on test/278_portable_airbin_config/test.cpp
> +// (c) Copyright 2021 Xilinx Inc. All Rights Reserved.
needs updated license

2022-12-21 01:45 UTC, fifield commented on test/279_dual_herd/test.cpp
> +// (c) Copyright 2021 Xilinx Inc. All Rights Reserved.
needs updated license

2022-12-21 01:45 UTC, fifield commented on test/300_relocatable_airbin_config/Makefile
> -# SPDX-License-Identifier: MIT
undelete license

2022-12-21 01:45 UTC, fifield commented on test/300_relocatable_airbin_config/test.cpp
> +// (c) Copyright 2021 Xilinx Inc. All Rights Reserved.
needs updated license

2022-12-21 01:45 UTC, fifield commented on test/301_airbin_gen_add_one/Makefile
> +ACDC_AIE = $(dir $(shell which aie-opt))/..
needs license

2022-12-21 01:45 UTC, fifield commented on test/301_airbin_gen_add_one/test.cpp
> +// (c) Copyright 2021 Xilinx Inc. All Rights Reserved.
needs updated license

2022-12-22 19:45 UTC, stephenneuendorffer commented on runtime_lib/airhost/airbin.cpp
> +airbin_size readairbinsize(std::ifstream &infile, uint8_t column_offset) {
camelcase or underscores?

2022-12-22 19:45 UTC, stephenneuendorffer commented on runtime_lib/airhost/airbin.cpp
> +void readairbin(std::ifstream &infile) {
underscores?

2022-12-23 14:55 UTC, fifield approved these changes

2022-12-23 14:55 UTC, fifield commented on runtime_lib/airhost/airbin.cpp
> +airbin_size readairbinsize(std::ifstream &infile, uint8_t column_offset) {
static?
+1 for underscores

2022-12-23 14:55 UTC, fifield commented on runtime_lib/airhost/airbin.cpp
> +uint64_t airbin2mem(std::ifstream &infile, volatile uint32_t *tds_va,
static?

2022-12-23 14:55 UTC, fifield commented on runtime_lib/airhost/airbin.cpp
> +void readairbin(std::ifstream &infile) {
static?

2023-08-24 17:28 UTC, jgmelber commented
Work continued by #259

2023-08-24 17:28 UTC, closed without merging