Update README.md
Xilinx/mlir-air pull request #201
Opened 2023-03-14 22:09 UTC by jnider

Fix the broken links.

2023-03-14 22:48 UTC, fifield requested changes
The links are setup to work here:
https://xilinx.github.io/mlir-air/

There might be a solution to make it work on both github.io and browsing the repo but I don't know it.

2023-03-14 22:54 UTC, stephenneuendorffer commented
I think the .md links with relative paths are transformed to .html links with relative paths when published to github.io: https://github.blog/2016-12-05-relative-links-for-github-pages/

2023-03-14 23:03 UTC, fifield commented
The generated mlir docs will never work browsing the repo unless we check them in but the platform docs can probably be reworked to work in both places. Here's the code that deploys them: https://github.com/Xilinx/mlir-air/blob/main/.github/workflows/generateDocs.yml#L93-L99 if anyone wants to play with it.

2023-03-15 00:42 UTC, jnider commented
I see, this seems to be a bigger issue than I thought. According to the explanation in Steve's link, the correct form is to write:
`[a relative link](another-page.md)`
Which gets translated to the appropriate HTML page automatically when published.
Is there a way to test github.io without checking in this commit?

2023-03-15 01:05 UTC, stephenneuendorffer commented
> The generated mlir docs will never work browsing the repo unless we check them in but the platform docs can probably be reworked to work in both places. Here's the code that deploys them: https://github.com/Xilinx/mlir-air/blob/main/.github/workflows/generateDocs.yml#L93-L99 if anyone wants to play with it.

Maybe use this instead? https://github.com/actions/deploy-pages

2023-03-15 01:06 UTC, stephenneuendorffer commented
> I see, this seems to be a bigger issue than I thought. According to the explanation in Steve's link, the correct form is to write: `[a relative link](another-page.md)` Which gets translated to the appropriate HTML page automatically when published. Is there a way to test github.io without merging this commit?

I don't think so, but I'd support experimenting here for a bit. We can always revert the changes.

2023-03-15 01:10 UTC, jackl-xilinx commented
@jnider You can experiment on your own fork and it'll build an associated github.io for it.

2023-03-17 01:51 UTC, jnider commented
I tested it on my own fork as @jackl-xilinx suggested and it works, according to the formatting in the link posted by @stephenneuendorffer .
You can see the .md files browsing the source tree here: https://github.com/jnider/mlir-air/tree/main/docs
And the .html files deployed on github.io (redirected to my personal domain name) here: http://joel.nider.org/mlir-air/

So at least those links can be updated but it doesn't solve the problem for the generated mlir docs.

2023-03-17 14:38 UTC, fifield commented on docs/README.md
> +- [Transform Dialect Extensions]
Revert this

2023-03-17 14:39 UTC, fifield commented on docs/README.md
> +#### [VCK5000 platform](../platforms/xilinx_vck5000_air)
Revert this

2023-03-17 22:49 UTC, fifield approved these changes

2023-03-17 23:01 UTC, fifield commented on docs/README.md
> +- [Transform Dialect Extensions]
The platform docs links will be broken after navigating to https://github.com/Xilinx/mlir-air/blob/main/docs/building.md directly, but when I set it up I thought it was nicer to have the platform specific docs be the `README.md` when navigating to `https://github.com/Xilinx/mlir-air/tree/main/platforms/<platform>`.  We could instead move the platform `README.md`s to the docs folder. Or maybe there are other suggestions?

2023-03-17 23:03 UTC, merged