Add libxaie paths to aiecc command lines
Xilinx/mlir-air pull request #235
Opened 2023-05-19 23:07 UTC by fifield

The defaults assumed by aiecc.py do not work for these tests.

2023-05-19 23:11 UTC, stephenneuendorffer requested changes
I don't understand, the libxaie dependency should be managed by aiecc.  This isn't the way to fix this, IMO

2023-05-19 23:15 UTC, fifield commented
> I don't understand, the libxaie dependency should be managed by aiecc. This isn't the way to fix this, IMO

I agree. These changes are to make the tests pass on my vck190. I'll gladly not merge them if we can fix aiecc instead.

2023-05-23 17:59 UTC, fifield commented
tracking this issue here: https://github.com/Xilinx/mlir-aie/issues/501

2023-06-14 00:03 UTC, fifield commented
This is likely fixed by https://github.com/Xilinx/mlir-air/pull/246

2023-08-15 18:36 UTC, fifield commented
obsolete

2023-08-15 18:36 UTC, closed without merging