Read write 32
Xilinx/mlir-air pull request #248
Opened 2023-06-20 23:17 UTC by eddierichter-amd

Adding functionality in the driver and runtime to generate read/write 32 packets to perform AIE configuration. In this implementation, the driver uses the first queue, which is mapped to the ARM, and can send read/write 32 packets to the firmware in response to read/write operations to the driver's sysfs interface. Currently still have the AIE BAR in the platform, which is unused but not hurting anything. Will remove that from the platform once we completely deprecate the MMIO configuration.

2023-06-20 23:36 UTC, jgmelber commented on runtime_lib/controller/main.cpp
> +#define CHATTY 1
CHATTY 0

2023-06-20 23:37 UTC, jgmelber commented
What version, if any, of libxaie does this need?

2023-06-20 23:41 UTC, eddierichter-amd commented
> What version, if any, of libxaie does this need?

From the host, it needs a libxaie backend which interacts with the driver's sysfs interface. This is implemented in Joel's fork.

2023-06-21 15:25 UTC, jgmelber requested changes

2023-06-21 15:42 UTC, eddierichter-amd commented on test/13_mb_add_one/Makefile
> +						-I$(ACDC_AIR)/runtime_lib/airhost/include -I$(ACDC_AIE)/runtime_lib/x86_64/test_lib/include $(ACDC_AIE)/runtime_lib/x86_64/test_lib/src/test_library.cpp \
Good point. 21 Makefile is updated here [2a56883](https://github.com/Xilinx/mlir-air/pull/248/commits/2a56883f8f751bc85444ed4a220f1b3d496fed95) added the others here [cb2e407](https://github.com/Xilinx/mlir-air/pull/248/commits/cb2e4076d2f1d7021b199dc5e9b35cff2154bf22).

2023-06-23 16:01 UTC, eddierichter-amd commented
> Can this be closed in light of #250 ?

Yep, closing now.

2023-06-23 16:01 UTC, closed without merging