Adding the AIR version of the weather stencil to the AIR repo
Xilinx/mlir-air pull request #260
Opened 2023-07-24 19:08 UTC by eddierichter-amd

Adding AIR versions of the 1 and 4 bblock designs to example directory.

2023-07-24 19:12 UTC, jgmelber requested changes
I think we need to also have the AMD license header on these files?

2023-07-24 19:12 UTC, jgmelber commented on examples/weather_stencil_air/hdiff_base.py
> +import numpy as np
License header?

2023-07-24 21:50 UTC, closed without merging

2023-07-25 18:09 UTC, fifield commented
Maybe I missed something, but I did not see any AIR design here?  I only found mlir-aie dialect...

2023-07-25 18:11 UTC, jgmelber commented
It's just the airrt data movement version of the stencil design using HSA packets