Weather stencil with AIR
Xilinx/mlir-air pull request #261
Opened 2023-07-27 23:00 UTC by singagan

2023-07-27 23:11 UTC, eddierichter-amd commented on examples/weather_stencil_air/aie_4.mlir
> +module @hdiff_bundle_4 {
We should make this one offset at column 2 as well.

2023-07-27 23:13 UTC, eddierichter-amd commented on examples/weather_stencil_air/four_bblock_output.txt
We can probably delete this, or at least update it with the new values.

2023-07-27 23:14 UTC, eddierichter-amd commented on examples/weather_stencil_air/hdiff_flux1.cc
> +// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
Think this snuck through. Guessing it is also the case for the other kernels.

2023-07-27 23:15 UTC, eddierichter-amd commented on examples/weather_stencil_air/hdiff_flux2.cc
> +// This file is licensed under the Apache License v2.0 with LLVM Exceptions.
Note.

2023-07-27 23:17 UTC, eddierichter-amd commented on examples/weather_stencil_air/single_bblock_output.txt
Again, we can probably remove this now.

2023-07-27 23:19 UTC, eddierichter-amd requested changes
Couple small updates.

2023-07-27 23:57 UTC, singagan commented
Fixed column offset and headers. Also, removed old output files.

2023-07-28 14:31 UTC, eddierichter-amd approved these changes
LGTM

2023-07-28 22:21 UTC, merged